- name: Updating apt package cache
  apt:
    update_cache: yes
- name: Installing openjdk-17-jdk
  apt:
    name: openjdk-17-jdk
    state: present
- name: Installing openjdk-17-jre
  apt:
    name: openjdk-17-jre
    state: present
